commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView

app_name = "commentapp"

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),

]

postapp/urls.py
from django.urls import path

from postapp.views import PostCreateView, PostUpdateView, PostDeleteView, PostDetailView, PostListView

app_name = "postapp"

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('list/', PostListView.as_view(), name='list'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from accountapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('posts/', include('postapp.urls')),
    path('dsums/', include('dsumapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('index/', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    #path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Post(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)

    type = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='post/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)



# class DSum(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class KQuestion(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class Contest(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class Major(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)

postapp/forms.py
from django.forms import ModelForm

from postapp.models import Post


class PostCreationForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'content']

postapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView
from django.views.generic.edit import FormMixin

from commentapp.forms import CommentCreationForm
from postapp.decorators import post_ownership_required
from postapp.forms import PostCreationForm
from postapp.models import Post


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class PostCreateView(CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = 'postapp/create.html'

    def form_valid(self, form):
        temp_post = form.save(commit=False)
        temp_post.writer = self.request.user
        temp_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('postapp:detail', kwargs={'pk': self.object.pk})

class PostDetailView(DetailView, FormMixin):
    model = Post
    form_class = CommentCreationForm
    context_object_name = 'target_post'
    template_name = 'postapp/detail.html'

    # def get_context_data(self, **kwargs):
    #     post = self.object
    #     user = self.request.user
    #
    #     #if user.is_authenticated: #로그인 했는가?
    #        #join = Join.objects.filter(user=user, project=project)
    #     #object_list = Post.object(project=self.get_object())
    #     return super(PostDetailView, self).get_context_data(object_list=object_list, **kwargs)
    #     #return super(PostDetailView, self).get_context_data(join=join, **kwargs)



@method_decorator(post_ownership_required, 'get')
@method_decorator(post_ownership_required, 'post')
class PostUpdateView(UpdateView):
    model = Post
    context_object_name = 'target_post'
    form_class = PostCreationForm
    template_name = 'postapp/update.html'

    def get_success_url(self):
        return reverse('postapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(post_ownership_required, 'get')
@method_decorator(post_ownership_required, 'post')
class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'target_post'
    success_url = reverse_lazy('postapp:list')
    template_name = 'postapp/delete.html'

class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'postapp/list.html'
    paginate_by = 25


#DetailView

# class DSumDetailView(DetailView):
#     model = DSum
#     context_object_name = 'target_dsum'
#     template_name = 'postapp/D-sum.html'
#
# class KQuestionDetailView(DetailView):
#     model = KQuestion
#     context_object_name = 'target_kquestion'
#     template_name = 'postapp/KQuestion.html'
#
# class ContestDetailView(DetailView):
#     model = Contest
#     context_object_name = 'target_contest'
#     template_name = 'postapp/contest.html'
#
# class MajorDetailView(DetailView):
#     model = Major
#     context_object_name = 'target_major'
#     template_name = 'postapp/major-tutoring.html'

#ListView

postapp/templates/postapp/D-sum.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
          <div class="sizejumbo-text">D-sum<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
      </div>
      <div id="w-node-e3f22483-798b-3788-463d-7441637cf85e-ae5f94eb" class="detail_page detail_component">
        <a href="#" class="size4-link">프로그램 신청 관련</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="e3f22483-798b-3788-463d-7441637cf86a" href="#" class="button-small register w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
      <div class="detail_page detail_component">
        <a href="#" class="size4-link">각종 서류 제출 관련 공지</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="12c9b3df-5f7a-b163-4e06-f872037b80f1" href="#" class="button-small submit w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
      <div class="detail_page detail_component">
        <a href="#" class="size4-link">기타 공지사항</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="f9ef15d0-6893-c5ae-03fd-813eda5bbe5d" href="#" class="button-small etc w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper login">
    <div class="footer1 login">
      <div class="section footer_top">
        <div class="w-layout-grid footer1-grid">
          <div class="div-block">
            <a href="index.html" class="size3-link">Sand Box<br></a>
            <div class="text-block-6">전자 및 정보공학과 비교과 웹</div>
          </div>
          <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f7f1-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">전체비교과</div>
            <a href="dsum-detail-page.html" class="footer1-link">- D-sum</a>
            <a href="1000q-detail-page.html" class="footer1-link">- 전공1000제</a>
            <a href="tutoring-detail-page.html" class="footer1-link">- 전공튜터링</a>
            <a href="#" class="footer1-link">- 공모전</a>
          </div>
          <div id="w-node-_315d7810-ba3f-ce55-f460-5bf0e6eb928c-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">기타</div>
            <a href="#" class="footer1-link">- Coworking</a>
            <a href="#" class="footer1-link">- 과학문화활동</a>
            <a href="#" class="footer1-link">- Data Refinery</a>
            <a href="#" class="footer1-link">- SFRG 링크연구회</a>
            <a href="#" class="footer1-link">- 캡스톤 프로그램</a>
            <a href="#" class="footer1-link">- Super Computing Center</a>
          </div>
          <div id="w-node-_39d9f504-cdd3-6364-ff83-207532bb1fb3-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">Pages</div>
            <a href="https://sejong.korea.ac.kr/kr" target="_blank" class="footer1-link">- 고려대학교 세종캠퍼스</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/index.do" target="_blank" class="footer1-link">- 전자 및 정보공학과</a>
            <a href="https://sportal.korea.ac.kr/" target="_blank" class="footer1-link">- 인재양성통합관리시스템</a>
            <a href="#" class="footer1-link">- KUHAS</a>
          </div>
          <div id="w-node-_01b7a166-099e-8765-751e-f97fb593708e-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text"> </div>
            <a href="https://sejong.korea.ac.kr/personal_information_policy" class="footer1-link">- 개인정보처리방침</a>
            <a href="https://sejong.korea.ac.kr/refusal_of_receiving_emails" class="footer1-link">- 이메일주소 무단수집거부</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/subview.do?id=kueie_010400000000" class="footer1-link">- 찾아오시는길</a>
          </div>
        </div>
      </div>
    </div>
    <div class="section footer_bottom">
      <div class="w-layout-grid footer1-bottom-grid">
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81b-c739f7eb">
          <div class="text-block-7">[30019] 세종특별자치시 세종로 2511 고려대학교 세종캠퍼스 과학기술1관 111B호</div>
          <div class="text-block-7 tel">TEL : 044-860-1350</div>
          <div class="text-block-7">Copyright ⓒ KOREA University Sejong Campus. All Rights Reserved | product by KUHAS</div>
        </div>
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81e-c739f7eb">
          <div class="nav-kit-wrap"><img src="images/crimson1positive.gif" loading="lazy" width="23" alt="" class="image-2">
            <a href="https://sejong.korea.ac.kr/kr" class="prospero-brand w-nav-brand">
              <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
              <div class="prospero-nav-logo under"><strong class="bold-text-3">KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
            </a>
            <div class="nav-kit-divider"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fdf5b16ab6df35ee79b9f8e" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
{% endblock %}

postapp/templates/postapp/KQuestion.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
          <div class="sizejumbo-text">전공 1000제<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
      </div>
      <div id="w-node-e3f22483-798b-3788-463d-7441637cf85e-ae5f94eb" class="detail_page detail_component">
        <a href="#" class="size4-link">프로그램 신청 관련</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="e3f22483-798b-3788-463d-7441637cf86a" href="#" class="button-small register w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
      <div class="detail_page detail_component">
        <a href="#" class="size4-link">각종 서류 제출 관련 공지</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="12c9b3df-5f7a-b163-4e06-f872037b80f1" href="#" class="button-small submit w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
      <div class="detail_page detail_component">
        <a href="#" class="size4-link">기타 공지사항</a>
        <div class="date_detail">
          <div class="text-label big">게시일 :</div>
          <div class="text-label date">2020/12/10</div>
          <div class="nav-kit-divider"></div>
          <div class="text-label big">신청마감일 :</div>
          <div class="text-label date">2020/12/31</div>
        </div>
        <div class="paragraph-70">------------------------------------------------------------------------------------------------------------------------------------------------------------------<br>--------------------------------------------------------------------------(내용 요약)------------------------------------------------------------------------------</div>
        <div class="blog1-button-wrap">
          <a data-w-id="f9ef15d0-6893-c5ae-03fd-813eda5bbe5d" href="#" class="button-small etc w-inline-block">
            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper login">
    <div class="footer1 login">
      <div class="section footer_top">
        <div class="w-layout-grid footer1-grid">
          <div class="div-block">
            <a href="index.html" class="size3-link">Sand Box<br></a>
            <div class="text-block-6">전자 및 정보공학과 비교과 웹</div>
          </div>
          <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f7f1-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">전체비교과</div>
            <a href="dsum-detail-page.html" class="footer1-link">- D-sum</a>
            <a href="1000q-detail-page.html" class="footer1-link">- 전공1000제</a>
            <a href="tutoring-detail-page.html" class="footer1-link">- 전공튜터링</a>
            <a href="#" class="footer1-link">- 공모전</a>
          </div>
          <div id="w-node-_315d7810-ba3f-ce55-f460-5bf0e6eb928c-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">기타</div>
            <a href="#" class="footer1-link">- Coworking</a>
            <a href="#" class="footer1-link">- 과학문화활동</a>
            <a href="#" class="footer1-link">- Data Refinery</a>
            <a href="#" class="footer1-link">- SFRG 링크연구회</a>
            <a href="#" class="footer1-link">- 캡스톤 프로그램</a>
            <a href="#" class="footer1-link">- Super Computing Center</a>
          </div>
          <div id="w-node-_39d9f504-cdd3-6364-ff83-207532bb1fb3-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">Pages</div>
            <a href="https://sejong.korea.ac.kr/kr" target="_blank" class="footer1-link">- 고려대학교 세종캠퍼스</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/index.do" target="_blank" class="footer1-link">- 전자 및 정보공학과</a>
            <a href="https://sportal.korea.ac.kr/" target="_blank" class="footer1-link">- 인재양성통합관리시스템</a>
            <a href="#" class="footer1-link">- KUHAS</a>
          </div>
          <div id="w-node-_01b7a166-099e-8765-751e-f97fb593708e-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text"> </div>
            <a href="https://sejong.korea.ac.kr/personal_information_policy" class="footer1-link">- 개인정보처리방침</a>
            <a href="https://sejong.korea.ac.kr/refusal_of_receiving_emails" class="footer1-link">- 이메일주소 무단수집거부</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/subview.do?id=kueie_010400000000" class="footer1-link">- 찾아오시는길</a>
          </div>
        </div>
      </div>
    </div>
    <div class="section footer_bottom">
      <div class="w-layout-grid footer1-bottom-grid">
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81b-c739f7eb">
          <div class="text-block-7">[30019] 세종특별자치시 세종로 2511 고려대학교 세종캠퍼스 과학기술1관 111B호</div>
          <div class="text-block-7 tel">TEL : 044-860-1350</div>
          <div class="text-block-7">Copyright ⓒ KOREA University Sejong Campus. All Rights Reserved | product by KUHAS</div>
        </div>
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81e-c739f7eb">
          <div class="nav-kit-wrap"><img src="images/crimson1positive.gif" loading="lazy" width="23" alt="" class="image-2">
            <a href="https://sejong.korea.ac.kr/kr" class="prospero-brand w-nav-brand">
              <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
              <div class="prospero-nav-logo under"><strong class="bold-text-3">KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
            </a>
            <div class="nav-kit-divider"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fdf5b16ab6df35ee79b9f8e" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
{% endblock %}

postapp/templates/postapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Post Create</h4>
    </div>
    <form action="{% url 'postapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

postapp/templates/postapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Post : {{ target_post.title }}</h4>
    </div>
    <form action="{% url 'postapp:delete' pk=target_post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

postapp/templates/postapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto">
       <h1>
           글 제목 : {{target_post.title}}
       </h1>
        <h4>
            글쓴이 : {{target_post.writer}}
        </h4>
        <h4>
            글 종류 : {{target_post.type}}
        </h4>
        <p>
            본문 : {{target_post.content}}
        </p>

        {% if target_post.image %}
            <img src="{{target_post.image.url}}" alt="">
        {% endif %}



        {% if target_post.writer == user %}
            <a href="{% url 'postapp:update' pk=target_post.pk %}">
                <p>Update Post</p>
            </a>
            <a href="{% url 'postapp:delete' pk=target_post.pk %}">
                <p>Delete Post</p>
            </a>
        {% endif %}

        <a href="{% url 'postapp:list' %}">
            <p>list</p>
        </a>
    <strong>comment</strong>
    <form action="{% url 'commentapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
    </div>
</div>
{% endblock %}

postapp/templates/postapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .container div {
    width: 250px;
    background-color: antiquewhite;
    display: flex;
    justify-content: center;
    align-items: center;

    border-radius: 1rem;
  }
  .container img {
    width:60%;
  }
</style>

<div class="container">
  {% for post in post_list %}
    <a href="{% url 'postapp:detail' pk=post.pk%}">
      <div>
        <div>
          {{post.title}}
        </div>
        <img src="{{ post.image.url}}" alt="" >
      </div>
    </a>
  {% endfor %}
<!--  <div><img src="https://picsum.photos/200/250"> </div>-->
<!--  <div><img src="https://picsum.photos/200/290"> </div>-->
<!--  <div><img src="https://picsum.photos/200/200"> </div>-->
<!--  <div><img src="https://picsum.photos/200/350"> </div>-->
<!--  <div><img src="https://picsum.photos/200/270"> </div>-->
<!--  <div><img src="https://picsum.photos/200/290"> </div>-->
<!--  <div><img src="https://picsum.photos/200/250"> </div>-->
<!--  <div><img src="https://picsum.photos/200/320"> </div>-->


</div>

{% endblock %}

postapp/templates/postapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Post Update</h4>
    </div>
    <form action="{% url 'postapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}