boardapp/urls.py
from django.urls import path

from boardapp.views import BoardCreateView, BoardUpdateView, BoardDetailView, BoardListView, BoardDeleteView, \
    NoticeListView, ContestListView, KquestionListView, DsumListView, TutoringListView

app_name = "boardapp"

urlpatterns = [
    path('create/', BoardCreateView.as_view(), name='create'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),

    path('list/', BoardListView.as_view(), name='list'),
    path('list/notice/', NoticeListView.as_view(), name='notice'),
    path('list/contest/', ContestListView.as_view(), name='contest'),
    path('list/kquestion/', KquestionListView.as_view(), name='kquestion'),
    path('list/dsum/', DsumListView.as_view(), name='dsum'),
    path('list/tutoring/', TutoringListView.as_view(), name='tutoring'),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from accountapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('posts/', include('postapp.urls')),
    path('dsums/', include('dsumapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('index/', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    #path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardapp/models.py
import re

from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Board(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='board', null=True)
    title = models.CharField(max_length=200, null=True)
    content = RichTextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    type_choice = [('notice',  '공지사항'), ('dsum', 'D-SUM'), ('kquestion', '전공 1000제'), ('contest', '공모전'), ('tutoring', '전공튜터링')]
    type = models.CharField(max_length=10, choices=type_choice, null=True)

    #def summary(self):
    #    if len(self.content) > 200:
    #        return self.content[:200] + ' ...'

    def temp(self):
        remove_tags = re.compile('<.*?>')
        if len(re.sub(remove_tags, '', self.content)) > 100:
            return re.sub(remove_tags, '', self.content)[:100] + ' ...'
        return re.sub(remove_tags, '', self.content)

postapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Post(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)

    type = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='post/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)



# class DSum(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class KQuestion(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class Contest(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)
#
# class Major(models.Model):
#     writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)
#     title = models.CharField(max_length=200, null=True)
#     content = models.TextField(null=True)
#
#     created_at = models.DateField(auto_now_add=True, null=True)

boardapp/forms.py
from django import forms
from django.forms import ModelForm

from boardapp import models
from boardapp.models import Board


class BoardCreationForm(ModelForm):
    #type = forms.ModelChoiceField(queryset=Board.objects.all(), required=False)

    class Meta:
        model = Board
        fields = ['title', 'type', 'content']

boardapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView

from boardapp.decorators import board_ownership_required
from boardapp.forms import BoardCreationForm
from boardapp.models import Board


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class BoardCreateView(CreateView):
    model = Board
    form_class = BoardCreationForm
    template_name = 'boardapp/create.html'

    def form_valid(self, form):
        temp_board = form.save(commit=False)
        temp_board.writer = self.request.user
        temp_board.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})

class BoardDetailView(DetailView):
    model = Board
    context_object_name = 'target_post'
    template_name = 'boardapp/detail.html'



    # def get_context_data(self, **kwargs):
    #     post = self.object
    #     user = self.request.user
    #
    #     #if user.is_authenticated: #로그인 했는가?
    #        #join = Join.objects.filter(user=user, project=project)
    #     #object_list = Post.object(project=self.get_object())
    #     return super(PostDetailView, self).get_context_data(object_list=object_list, **kwargs)
    #     #return super(PostDetailView, self).get_context_data(join=join, **kwargs)



@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardUpdateView(UpdateView):
    model = Board
    context_object_name = 'target_post'
    form_class = BoardCreationForm
    template_name = 'boardapp/update.html'

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardDeleteView(DeleteView):
    model = Board
    context_object_name = 'target_post'
    success_url = reverse_lazy('boardapp:list')
    template_name = 'boardapp/delete.html'



class BasicListView(ListView):
    model = Board
    context_object_name = 'post_list'

    #template_name = 'boardapp/notice.html'
    paginate_by = 25

    ordering = ['-id']



class BoardListView(BasicListView):
    template_name = 'boardapp/list.html'



class NoticeListView(BasicListView):
    template_name = 'boardapp/notice.html'

    def get_queryset(self):
        temp = []
        board_all = Board.objects.all()
        for board in board_all:
            if board.type == 'notice':
                temp.append(board)
        board_temp = temp
        page = int(self.request.GET.get('p', 1))
        paginator = Paginator(board_temp, 3)
        queryset = paginator.get_page(page)
        return queryset

class ContestListView(BasicListView):
    template_name = 'boardapp/contest.html'


class KquestionListView(BasicListView):
    template_name = 'boardapp/kquestion.html'


class TutoringListView(BasicListView):
    template_name = 'boardapp/tutoring.html'


class DsumListView(BasicListView):
    template_name = 'boardapp/dsum.html'

boardapp/templates/boardapp/contest.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">공모전<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
      {% for post in post_list %}
        {% if post.type == 'contest' %}
          {% include 'post.html' %}
        {% endif %}
      {% endfor %}
    </div>
  </div>

</body>
{% endblock %}

boardapp/templates/boardapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Board Create</h4>
    </div>
    <form action="{% url 'boardapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>

</div>
{% endblock %}

boardapp/templates/boardapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Post : {{ target_post.title }}</h4>
    </div>
    <form action="{% url 'boardapp:delete' pk=target_post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

boardapp/templates/boardapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto">
       <h1>
           <strong>글 제목 : {{target_post.title}}</strong>
       </h1>
        <h4>
            글쓴이 : {{target_post.writer}}
        </h4>

        <hr>
        <p>
            종류 : {{target_post.type}}
        </p>
        <p>
            본문 : {{target_post.content | safe}}
        </p>

        <hr>
        <br>
        <br>
        {% if target_post.writer == user %}
            <a href="{% url 'boardapp:update' pk=target_post.pk %}">
                <p>Update Post</p>
            </a>
            <a href="{% url 'boardapp:delete' pk=target_post.pk %}">
                <p>Delete Post</p>
            </a>
        {% endif %}

        {% if target_post.type  == 'notice'%}
            <a href="{% url 'boardapp:notice' %}">
        {% endif %}
        {% if target_post.type  == 'dsum'%}
            <a href="{% url 'boardapp:dsum' %}">
        {% endif %}
        {% if target_post.type  == 'kquestion'%}
            <a href="{% url 'boardapp:kquestion' %}">
        {% endif %}
        {% if target_post.type  == 'contest'%}
            <a href="{% url 'boardapp:contest' %}">
        {% endif %}
        {% if target_post.type  == 'tutoring'%}
            <a href="{% url 'boardapp:tutoring' %}">
        {% endif %}
            <p>list</p>
        </a>
    </div>
</div>
{% endblock %}

boardapp/templates/boardapp/dsum.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">D-SUM<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
      {% for post in post_list %}
        {% if post.type == 'dsum' %}
          {% include 'post.html' %}
        {% endif %}
      {% endfor %}
    </div>
  </div>


</body>
{% endblock %}

boardapp/templates/boardapp/kquestion.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">전공 1000제<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
      {% for post in post_list %}
        {% if post.type == 'kquestion' %}
          {% include 'post.html' %}
        {% endif %}
      {% endfor %}
    </div>
  </div>


</body>
{% endblock %}

boardapp/templates/boardapp/list.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">전체 게시판<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
      {% for post in post_list %}
        {% include 'post.html' %}
      {% endfor %}
<!--      <div class="detail_page detail_component">-->
<!--        <a href="#" class="size4-link">각종 서류 제출 관련 공지</a>-->
<!--        <div class="date_detail">-->
<!--          <div class="text-label big">게시일 :</div>-->
<!--          <div class="text-label date">2020/12/10</div>-->
<!--          <div class="nav-kit-divider"></div>-->
<!--          <div class="text-label big">신청마감일 :</div>-->
<!--          <div class="text-label date">2020/12/31</div>-->
<!--        </div>-->
<!--        <div class="paragraph-70">&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;<br>&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;(내용 요약)&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</div>-->
<!--        <div class="blog1-button-wrap">-->
<!--          <a data-w-id="12c9b3df-5f7a-b163-4e06-f872037b80f1" href="#" class="button-small submit w-inline-block">-->
<!--            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">-->
<!--          </a>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="detail_page detail_component">-->
<!--        <a href="#" class="size4-link">기타 공지사항</a>-->
<!--        <div class="date_detail">-->
<!--          <div class="text-label big">게시일 :</div>-->
<!--          <div class="text-label date">2020/12/10</div>-->
<!--          <div class="nav-kit-divider"></div>-->
<!--          <div class="text-label big">신청마감일 :</div>-->
<!--          <div class="text-label date">2020/12/31</div>-->
<!--        </div>-->
<!--        <div class="paragraph-70">&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;<br>&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;(내용 요약)&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</div>-->
<!--        <div class="blog1-button-wrap">-->
<!--          <a data-w-id="f9ef15d0-6893-c5ae-03fd-813eda5bbe5d" href="#" class="button-small etc w-inline-block">-->
<!--            <div class="button-label">Read more</div><img src="images/Arrow2x.svg" alt="" class="button-arrow">-->
<!--          </a>-->
<!--        </div>-->
<!--      </div>-->


</body>
{% endblock %}

boardapp/templates/boardapp/notice.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">공지사항<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
        {% for post in post_list %}
          {% if post.type == 'notice' %}
            {% include 'post.html' %}
          {% endif %}
        {% endfor %}
    </div>
  </div>

 <!-- <div class="row mt-2">
          <div class="col-12">
              <nav>
                  <ul class="pagination justify-content-center">
                      <h1> hello : {{post_list.has_previous}}</h1>
                      {% if post_list.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?p={{post_list.previous_page_number }}">h이전으로</a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#">이전으로</a>
                      </li>
                      {% endif %}
                      <li class="page-item">
                          <a class="page-link" href="#">{{post_list.number}}/{{post_list.paginator.num_pages}}</a>
                      </li>
                      {% if post_list.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?p={{post_list.next_page_number }}">h다음으로</a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#">다음으로</a>
                      </li>
                      {% endif %}
                  </ul>
              </nav>
          </div>
      </div>
-->

<div class="row mt-2">
          <div class="col-12">
              <nav>
                  <ul class="pagination justify-content-center">
                      <span class="page-item">
                          <a class="page-link" href="{% url 'boardapp:notice' %}?p=1">1페이지</a>
                      </span>
                      <span class="page-item">
                          <a class="page-link" href="{% url 'boardapp:notice' %}?p=2">2페이지</a>
                      </span>
                      <span class="page-item">
                          <a class="page-link" href="{% url 'boardapp:notice' %}?p=3">3페이지</a>
                      </span>
                  </ul>
              </nav>
          </div>
      </div>
</body>

{% endblock %}

boardapp/templates/boardapp/tutoring.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div class="elements-section-headline-wrap notice">
    <div id="Hero" class="section detail">
      <div class="w-layout-grid grid">
        <div id="w-node-_7dda8885-ea4b-3585-181f-391edaf00c22-ae5f94eb" class="elements-headline-wrap">
            <div class="sizejumbo-text">전공 튜터링<br></div>
          <p class="detail_page">전자 및 정보공학과 <br>비교과 프로그램 전체 공지사항</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="w-layout-grid blog1-grid">
      <div id="w-node-_4cdac5a5-6ceb-cb09-5bb0-11da51d85b8a-ae5f94eb" class="blog1-headline-wrap detail_page">
        <div class="size3-text">All Posts<br></div>
        <a href="{% url 'boardapp:create' %}"><button><div>post</div></button></a>
      </div>
      {% for post in post_list %}
        {% if post.type == 'tutoring' %}
          {% include 'post.html' %}
        {% endif %}
      {% endfor %}
    </div>
  </div>


</body>
{% endblock %}

boardapp/templates/boardapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Post Update</h4>
    </div>
    <form action="{% url 'boardapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}