accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, index

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('index/', index, name='index'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from accountapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('posts/', include('postapp.urls')),
    path('dsums/', include('dsumapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('index/', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    #path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.utils.decorators import method_decorator

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_ownership = [account_ownership_required, login_required]

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView


def index(request):
    return render(request, 'accountapp/index.html')



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto">
       <p>
           {{target_user.date_joined}}
       </p>
            <img src="/static/images/crimson1positive.gif" loading="lazy" width="23rem" alt="" class="image-2">
        <!--대상의 프로필이 있는가-->
        {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="" style="height:10rem; width:10rem; border-radius: 20rem; margin-bottom: 1rem;">

            <h2>
                {{target_user.profile.nickname}}
                <!--유저 본인인가-->
                {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                        edit
                    </a>
                {% endif %}
                <h5 style="margin-bottom: 3rem">
                    {{ target_user.profile.message }}
                </h5>

            </h2>

            {% if target_user == user %}
            <a href="{% url 'profileapp:update' pk=user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
            {% endif %}

        <!--대상 프로필이 없다면,-->
        {% else %}
        <div>user : {{ target_user }}</div>
        <div>user email : {{ target_user.email }}</div>
        <div>user id : {{ target_user.pk }}</div>
        <div>username : {{ target_user.username }}</div>
        <div>first name : {{ target_user.first_name }}</div>
        <div>last name : {{ target_user.last_name }}</div>
        <div>is active : {{ target_user.is_active }}</div>
        <div>date joined : {{ target_user.date_joined }}</div>
        <div>USERNAME_FIELD : {{ target_user.USERNAME_FIELD }}</div>
        {{googleUser}}
            <!--유저 본인이면,-->
            {% if target_user == user %}
            <a href="{% url 'profileapp:create'%}">
                <h2>
                    Create Profile
                </h2>
            </a>
            <!--유저 본인 아니면,-->
            {% else %}
                <h2>
                    닉네임 미설정
                </h2>
            {% endif %}
        {% endif %}

        {% if target_user == user %}

            <a href="{% url 'accountapp:delete' pk=user.pk %}">
                <p>
                    Quit
                </p>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span>logout</span>
            </a>

        {% endif %}

<!--        <div>-->
<!--            <h2>프로젝트 프레임</h2>-->
<!--            {% for project in project_list %}-->
<!--                {% if project.writer == target_user %}-->
<!--                <h4>{{project.title}}</h4>-->
<!--                <img src="{{project.image1.url}}" style="height:10rem; width:10rem;">-->
<!--                <h4>{{project.content}}</h4>-->
<!--                <h4>{{project.created_at}}</h4>-->
<!--                {% endif %}-->
<!--            {% endfor %}-->
<!--        </div>-->

<!--        <div>-->
<!--            <h2>프로젝트 프레임2</h2>-->
<!--            {% for join in join_list %}-->
<!--                {% if join.user == target_user %}-->
<!--                <h2>{{join.user}}</h2>-->
<!--                <h4>{{join.project.title}}</h4>-->
<!--                <img src="{{join.project.image1.url}}" style="height:10rem; width:10rem;">-->
<!--                <h4>{{join.project.content}}</h4>-->
<!--                <h4>{{join.project.created_at}}</h4>-->
<!--                {% endif %}-->
<!--            {% endfor%}-->
<!--        </div>-->




    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/home.html
{% extends 'base.html' %}
{% block content %}
    <div style="border-radius: 1rem; margin: 2rem; text-align:center">
        <h1 style="font-family: 'Galada', cursive;">Hello World List</h1>
        <div style="height:30rem; width:50rem; background-color: #38df81;"></div>
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div>
        <h4>Login</h4>
    </div>
    <div>

        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">

        </form>
        <a href="/accounts/google/login/">
            <button class="btn btn-dark rounded-pill col-6 mt-3"> Google Login </button>
        </a>

    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>ChangeInfo</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}