accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, index

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('index/', index, name='index'),
]

boardapp/urls.py
from django.urls import path

from boardapp.views import BoardCreateView, BoardUpdateView, BoardDetailView, BoardListView, BoardDeleteView, \
    NoticeListView, ContestListView, KquestionListView, DsumListView, TutoringListView

app_name = "boardapp"

urlpatterns = [
    path('create/', BoardCreateView.as_view(), name='create'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),

    path('list/', BoardListView.as_view(), name='list'),
    path('list/notice/', NoticeListView.as_view(), name='notice'),
    path('list/contest/', ContestListView.as_view(), name='contest'),
    path('list/kquestion/', KquestionListView.as_view(), name='kquestion'),
    path('list/dsum/', DsumListView.as_view(), name='dsum'),
    path('list/tutoring/', TutoringListView.as_view(), name='tutoring'),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from accountapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('posts/', include('postapp.urls')),
    path('dsums/', include('dsumapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('index/', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    #path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Wed Jul 21 2021 05:43:07 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5fe159195219fd29ae5f94eb" data-wf-site="5fdf5b16ab6df35ee79b9f8e">
{% include 'head.html' %}

    {% include 'header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</html>

templates/footer.html
</div>
</div>
  <div class="wrapper login">
    <div class="footer1 login">
      <div class="section footer_top">
        <div class="w-layout-grid footer1-grid">
          <div class="div-block">
            <a href="{% url 'index' %}" aria-current="page" class="size3-link w--current">Sand Box<br></a>
            <div class="text-block-6">전자 및 정보공학과 비교과 웹</div>
          </div>
          <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f7f1-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">전체비교과</div>
            <a href="{% url 'boardapp:dsum' %}" class="footer1-link">- D-sum</a>
            <a href="{% url 'boardapp:kquestion' %}" class="footer1-link">- 전공1000제</a>
            <a href="{% url 'boardapp:tutoring' %}" class="footer1-link">- 전공튜터링</a>
            <a href="{% url 'boardapp:contest' %}" class="footer1-link">- 공모전</a>
          </div>
          <div id="w-node-_315d7810-ba3f-ce55-f460-5bf0e6eb928c-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">기타</div>
            <a href="#" class="footer1-link">- Coworking</a>
            <a href="#" class="footer1-link">- 과학문화활동</a>
            <a href="#" class="footer1-link">- Data Refinery</a>
            <a href="#" class="footer1-link">- SFRG 링크연구회</a>
            <a href="#" class="footer1-link">- 캡스톤 프로그램</a>
            <a href="#" class="footer1-link">- Super Computing Center</a>
          </div>
          <div id="w-node-_39d9f504-cdd3-6364-ff83-207532bb1fb3-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">Pages</div>
            <a href="https://sejong.korea.ac.kr/kr" target="_blank" class="footer1-link">- 고려대학교 세종캠퍼스</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/index.do" target="_blank" class="footer1-link">- 전자 및 정보공학과</a>
            <a href="https://sportal.korea.ac.kr/" target="_blank" class="footer1-link">- 인재양성통합관리시스템</a>
            <a href="#" class="footer1-link">- KUHAS</a>
          </div>
          <div id="w-node-_01b7a166-099e-8765-751e-f97fb593708e-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text"> </div>
            <a href="https://sejong.korea.ac.kr/personal_information_policy" target="_blank" class="footer1-link">- 개인정보처리방침</a>
            <a href="https://sejong.korea.ac.kr/refusal_of_receiving_emails" target="_blank" class="footer1-link">- 이메일주소 무단수집거부</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/subview.do?id=kueie_010400000000" target="_blank" class="footer1-link">- 찾아오시는길</a>
          </div>
        </div>
      </div>
    </div>
    <div class="section footer_bottom">
      <div class="w-layout-grid footer1-bottom-grid">
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81b-c739f7eb">
          <div class="text-block-7">[30019] 세종특별자치시 세종로 2511 고려대학교 세종캠퍼스 과학기술1관 111B호</div>
          <div class="text-block-7 tel">TEL : 044-860-1350</div>
          <div class="text-block-7">Copyright ⓒ KOREA University Sejong Campus. All Rights Reserved | product by KUHAS</div>
        </div>
        <div id="w-node-_2d8a3600-59cf-08d2-fe17-bd16c739f81e-c739f7eb">
          <div class="nav-kit-wrap"><img src="images/crimson1positive.gif" loading="lazy" width="23" alt="" class="image-2">
            <a href="https://sejong.korea.ac.kr/kr" target="_blank" class="prospero-brand w-nav-brand">
              <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
              <div class="prospero-nav-logo under"><strong class="bold-text-3">KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
            </a>
            <div class="nav-kit-divider"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
<script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fdf5b16ab6df35ee79b9f8e" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->

templates/head.html
{% load static %}
<head>
  <base href="/static/">

  <meta charset="utf-8">
  <title>notice_detail_page</title>

<!--  code block-->
  <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/styles/monokai-sublime.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>



  <meta content="Pick and choose from 5 different blog feed layouts. Use the Prospero UI Kit to create fast and free web designs." name="description">
  <meta content="notice_detail_page" property="og:title">
  <meta content="Pick and choose from 5 different blog feed layouts. Use the Prospero UI Kit to create fast and free web designs." property="og:description">
  <meta content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png" property="og:image">
  <meta content="notice_detail_page" property="twitter:title">
  <meta content="Pick and choose from 5 different blog feed layouts. Use the Prospero UI Kit to create fast and free web designs." property="twitter:description">
  <meta content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png" property="twitter:image">
  <meta property="og:type" content="website">
  <meta content="summary_large_image" name="twitter:card">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href="css/normalize.css" rel="stylesheet" type="text/css">
  <link href="css/webflow.css" rel="stylesheet" type="text/css">
  <link href="css/final-2c3dd8-a747bae44c98-22507a1374e85.webflow.css" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({  google: {    families: ["Work Sans:100,200,300,regular,500,600,700,800,900"]  }});</script>
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="images/webclip.png" rel="apple-touch-icon">
</head>

templates/header.html
<div data-collapse="medium" data-animation="default" data-duration="400" data-easing2="ease-in-out-circ" data-easing="ease-out-circ" id="navigation" role="banner" class="navbar w-nav">
    <div class="nav-kit-wrap"><img src="images/crimson1positive.gif" loading="lazy" width="23" alt="" class="image-2">
      <a href="http://sejong.korea.ac.kr" target="_blank" class="prospero-brand w-nav-brand">
        <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
        <div class="prospero-nav-logo under"><strong>KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
      </a>
      <div class="nav-kit-divider"></div>
    </div>
    <nav role="navigation" class="nav-menu w-nav-menu">
      <div class="dropdowns-wrap">
        <div data-hover="1" data-delay="0" class="dropdown w-dropdown">
          <div class="dropdown-toggle w-dropdown-toggle">
            <div class="dropdown-wrap">
              <div class="prospero-link">전체비교과</div><img src="images/Dropdown-Arrow2x.svg" alt="" class="kit-arrow-dropdown">
            </div>
          </div>
          <nav class="dropdown-list w-dropdown-list">
            <div>
              <a href="{% url 'boardapp:list' %}" class="dropdown-link w-dropdown-link">전체 게시판</a>
              <a href="{% url 'boardapp:notice' %}" class="dropdown-link w-dropdown-link">공지사항</a>
              <a href="{% url 'boardapp:dsum' %}" class="dropdown-link w-dropdown-link">d-sum</a>
              <a href="{% url 'boardapp:kquestion' %}" class="dropdown-link w-dropdown-link">전공1000제</a>
              <a href="{% url 'boardapp:tutoring' %}" class="dropdown-link w-dropdown-link">전공튜터링</a>
              <a href="{% url 'boardapp:contest' %}" class="dropdown-link w-dropdown-link">공모전</a>
            </div>
          </nav>
        </div>
        <div data-hover="1" data-delay="0" class="dropdown w-dropdown">
          <div class="dropdown-toggle w-dropdown-toggle">
            <div class="dropdown-wrap">
              <div class="prospero-link">기타</div><img src="images/Dropdown-Arrow2x.svg" alt="" class="kit-arrow-dropdown">
            </div>
          </div>
          <nav class="dropdown-list w-dropdown-list">
            <div>
              <a href="#" class="dropdown-link w-dropdown-link">Co-Working</a>
              <a href="#" class="dropdown-link w-dropdown-link">과학문화활동</a>
              <a href="#" class="dropdown-link w-dropdown-link">Data Refinery Center</a>
            </div>
            <div>
              <a href="#" class="dropdown-link w-dropdown-link">sFGR 링크 연구회</a>
              <a href="#" class="dropdown-link w-dropdown-link">캡스톤 프로그램</a>
              <a href="#" class="dropdown-link w-dropdown-link">Super Computing Center</a>
            </div>
          </nav>
        </div>
      </div>
    </nav>
  {% if not user.is_authenticated %}
    <div class="kit-nav-buttons-wrap">
      <a data-w-id="cb8ec73b-92b3-c27d-4e84-2e9d121a0e07" href="{% url 'accountapp:login' %}" target="_self" class="button-small kit-download-menu w-inline-block">
        <div class="button-label">Login</div>
      </a>
    </div>
  {% else %}
    <div class="kit-nav-buttons-wrap">
      <a data-w-id="cb8ec73b-92b3-c27d-4e84-2e9d121a0e07" href="{% url 'accountapp:logout' %}" target="_self" class="button-small kit-download-menu w-inline-block">
        <div class="button-label">Logout</div>
      </a>
    </div>
  {% endif %}

    <div data-w-id="ae2b4f16-c826-fbf0-1743-c29e48bda8e9" class="menu-button-kit menu-button-kit-nav w-nav-button"><img src="images/Menu-Icon_1Menu-Icon.png" height="14" width="20" alt="" class="menu-icon-kit-nav"><img src="images/Menu-Icon_1Menu-Icon.png" height="14" width="20" alt="" class="menu-icon-swipe"></div>
  </div>